language: ruby
rvm:
- 2.1
sudo: required

# install jekyll from gemfile
install: 
   - chmod +x ./scripts/dropbox.sh
   - ./scripts/dropbox.sh
   - bundle install
   - rake

# build site
scripts: true

# deploy to surge
after_success: 
   - npm install --save-dev surge
   - chmod +x ./scripts/deploy.sh
   - ./scripts/deploy.sh

# branch whitelist, only for GitHub Pages
branches:
  only:
  - master
